on:
  push:

name: lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          package-manager-cache: false
      - name: enable corepack
        run: corepack enable
      - name: yarn set v4
        run: yarn set version stable
      - name: yarn install
        run: yarn install
      - name: Run eslint
        run: yarn lint
      - name: Run format
        run: yarn format
      # - name: Run test:cov
      #   run: yarn test:cov
