name: deploy-github-actions
# トリガーの設定
on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest # 実行環境の設定
    steps:
    - name: Tailscale
      uses: tailscale/github-action@d1b6cd204f8dceda5b3eaad7f1f767be390056cd # v4
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:cicd
    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1
      with:
        key: ${{ secrets.KEY }}
        host: ${{secrets.HOST}}
        username: ${{secrets.SSH_USER}}
        passphrase: ${{secrets.SSH_PASSPHRASE}}
        port: ${{secrets.PORT}}
        script: |
          cd portofolio
          git pull origin main
          yarn install 
          yarn build
          sudo rm -rf /usr/share/nginx/html/demo/dist
          sudo mv dist /usr/share/nginx/html/demo/
          sudo semanage fcontext -a -t httpd_sys_content_t "/usr/share/nginx/html/demo/dist(/.*)?"
          sudo restorecon -Rv /usr/share/nginx/html/demo/dist
          
